### ISSUE TITLE
hexo-renderer-pandoc is updated.

### ISSUE THREAD

**Issue by satorf** [thcd/hexo-katex#4]
Could you please update the readme to use new `hexo-renderer-pandoc` option?

`hexo-renderer-pandoc` is updated and `mathEngine` config option is added.
By this option, you can choose the math engine to pass to the pandoc args.

So, now you don't have to edit the source code of `hexo-renderer-pandoc` directly when use `hexo-katex`.
The only thing you have to do is to add `_config.yml` to this:
```
pandoc:
  mathEngine: katex
```
Then `hexo-katex` will be work fine.

**Comment by thcd** [comment]
Updated. Thank you.
