### ISSUE TITLE
Works on posts, but not on index page.

### ISSUE THREAD

**Issue by sierxue** [thcd/hexo-katex#6]
Thanks first for your wonderful package!

I am using theme hexo-theme-next,  one of the most popular themes. Your package works on all posts pages, but on the index page, katex does not render. 

How can I fix it?

**Comment by thcd** [comment]
This plugin uses [`after_post_render`](https://hexo.io/api/filter.html#after-post-render) so it only works on posts content. I have no idea how to render index page now.

**Comment by sierxue** [comment]
Nevertheless, the plugin is great enough to use. Thank you for your good job!
